# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protofile.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protofile.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fprotofile.proto\"f\n\x0b\x44\x61taRequest\x12\r\n\x05x_min\x18\x01 \x01(\x01\x12\r\n\x05x_max\x18\x02 \x01(\x01\x12\r\n\x05y_min\x18\x03 \x01(\x01\x12\r\n\x05y_max\x18\x04 \x01(\x01\x12\x0c\n\x04time\x18\x05 \x01(\x03\x12\r\n\x05steps\x18\x06 \x01(\x03\"\x13\n\x06xarray\x12\t\n\x01x\x18\x01 \x03(\x01\"\x13\n\x06yarray\x12\t\n\x01y\x18\x01 \x03(\x01\"\x13\n\x06zarray\x12\t\n\x01z\x18\x01 \x03(\x01\"J\n\x0c\x44\x61taResponse\x12\x12\n\x01x\x18\x01 \x03(\x0b\x32\x07.xarray\x12\x12\n\x01y\x18\x02 \x03(\x0b\x32\x07.yarray\x12\x12\n\x01z\x18\x03 \x03(\x0b\x32\x07.zarray2;\n\x0f\x43omputeFunction\x12(\n\x07\x63ompute\x12\x0c.DataRequest\x1a\r.DataResponse0\x01\x62\x06proto3'
)




_DATAREQUEST = _descriptor.Descriptor(
  name='DataRequest',
  full_name='DataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_min', full_name='DataRequest.x_min', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x_max', full_name='DataRequest.x_max', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y_min', full_name='DataRequest.y_min', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y_max', full_name='DataRequest.y_max', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='DataRequest.time', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='steps', full_name='DataRequest.steps', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=121,
)


_XARRAY = _descriptor.Descriptor(
  name='xarray',
  full_name='xarray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='xarray.x', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=142,
)


_YARRAY = _descriptor.Descriptor(
  name='yarray',
  full_name='yarray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='y', full_name='yarray.y', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=163,
)


_ZARRAY = _descriptor.Descriptor(
  name='zarray',
  full_name='zarray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='z', full_name='zarray.z', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=184,
)


_DATARESPONSE = _descriptor.Descriptor(
  name='DataResponse',
  full_name='DataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='DataResponse.x', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='DataResponse.y', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='DataResponse.z', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=260,
)

_DATARESPONSE.fields_by_name['x'].message_type = _XARRAY
_DATARESPONSE.fields_by_name['y'].message_type = _YARRAY
_DATARESPONSE.fields_by_name['z'].message_type = _ZARRAY
DESCRIPTOR.message_types_by_name['DataRequest'] = _DATAREQUEST
DESCRIPTOR.message_types_by_name['xarray'] = _XARRAY
DESCRIPTOR.message_types_by_name['yarray'] = _YARRAY
DESCRIPTOR.message_types_by_name['zarray'] = _ZARRAY
DESCRIPTOR.message_types_by_name['DataResponse'] = _DATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataRequest = _reflection.GeneratedProtocolMessageType('DataRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATAREQUEST,
  '__module__' : 'protofile_pb2'
  # @@protoc_insertion_point(class_scope:DataRequest)
  })
_sym_db.RegisterMessage(DataRequest)

xarray = _reflection.GeneratedProtocolMessageType('xarray', (_message.Message,), {
  'DESCRIPTOR' : _XARRAY,
  '__module__' : 'protofile_pb2'
  # @@protoc_insertion_point(class_scope:xarray)
  })
_sym_db.RegisterMessage(xarray)

yarray = _reflection.GeneratedProtocolMessageType('yarray', (_message.Message,), {
  'DESCRIPTOR' : _YARRAY,
  '__module__' : 'protofile_pb2'
  # @@protoc_insertion_point(class_scope:yarray)
  })
_sym_db.RegisterMessage(yarray)

zarray = _reflection.GeneratedProtocolMessageType('zarray', (_message.Message,), {
  'DESCRIPTOR' : _ZARRAY,
  '__module__' : 'protofile_pb2'
  # @@protoc_insertion_point(class_scope:zarray)
  })
_sym_db.RegisterMessage(zarray)

DataResponse = _reflection.GeneratedProtocolMessageType('DataResponse', (_message.Message,), {
  'DESCRIPTOR' : _DATARESPONSE,
  '__module__' : 'protofile_pb2'
  # @@protoc_insertion_point(class_scope:DataResponse)
  })
_sym_db.RegisterMessage(DataResponse)



_COMPUTEFUNCTION = _descriptor.ServiceDescriptor(
  name='ComputeFunction',
  full_name='ComputeFunction',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=262,
  serialized_end=321,
  methods=[
  _descriptor.MethodDescriptor(
    name='compute',
    full_name='ComputeFunction.compute',
    index=0,
    containing_service=None,
    input_type=_DATAREQUEST,
    output_type=_DATARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMPUTEFUNCTION)

DESCRIPTOR.services_by_name['ComputeFunction'] = _COMPUTEFUNCTION

# @@protoc_insertion_point(module_scope)
